Fix dirt 3 outside of steam
Open-Wine-Components/umu-protonfixes pull request #159
Opened 2024-11-14 00:02 UTC by polluxau

Without this library (openal) dirt 3 wont launch on proton 8 or above

This is for running the game on its own with no store available

2024-11-22 20:57 UTC, R1kaB3rN requested changes

2024-11-22 20:57 UTC, R1kaB3rN commented on gamefixes-umu/umu-321040.py
> +    util.protontricks('Openal')
Instead of a file, this should be a symbolic link to the corresponding Steam fix

2024-11-22 20:58 UTC, R1kaB3rN commented
I won't ask how you acquired this game. But this game is broken under Proton so I'm fine with creating this fix.

2024-11-23 01:29 UTC, polluxau commented
> I won't ask how you acquired this game. But this game is broken under Proton and we already had a fix for it, so I'm fine with creating this fix.

Do you want the symbolic link still?

2024-11-23 18:42 UTC, R1kaB3rN commented on gamefixes-umu/umu-321040.py
> +    util.protontricks('Openal')
This needs to be deleted. Remove the file locally then commit and force push your changes.

2024-11-23 18:57 UTC, R1kaB3rN commented
> Question also, if its a symbolic link the file is 321040.py, will it still be detected if its like that on a copy of dirt 3 outside of steam from no store?

Yes, but detection and usage of the fix depends. 

The entire system of applying fixes relies on metadata being available and the user/client giving umu that info. For example, when setting `GAMEID=umu-0` and `STORE=none` or `STORE=`, by default, the module will search the `umu-database.csv` for `umu-0`. On the other hand, if the client (e.g., Lutris) sets the ID and store, then protonfixes may not apply the fix.

2024-11-24 00:31 UTC, polluxau commented on gamefixes-umu/321040.py
> +/home/pollux/umu-protonfixes-dirt3/gamefixes-steam/321040.py
I see, thank you for the help :)

2024-11-24 07:04 UTC, R1kaB3rN approved these changes

2024-11-24 07:07 UTC, merged